### PR TITLE
PP-2573

### PR DESCRIPTION
**Pull request by Kevmo92**
https://ncinodev.atlassian.net/browse/PP-2573

We'll want to replicate this logic in other projects once we've built out the stubbed scripts.
jira_updater.py needs to be enhanced to handle updating the status.

Tickets PROD-12525 and PROD-11438 can be used for testing. Ensure that the tickets are in a `In Review` status in order for the status update to work.

The json data being sent to the build should be structured like this:
```
{
  "build_parameters": {
    "CIRCLE_JOB": "deploy_to_release_only",
    "DYNAMODB_DEPLOYMENT_RECORD_ID": "uniqueID",
    "UPDATE_JIRA_ISSUES": "true",
    "JIRA_ISSUES": "PROD-12525,PROD-11438",
    "JIRA_UPDATER_REVERT_CHANGES": "{\"fixVersions\": [{\"remove\": \"testing-the-cloud-9.0.0\"}, {\"add\": \"testing-the-cloud-9.0.1\"}]}",
    "TRIGGER_PACKAGE_BUILD": "true"
  }
}
```
To test this out, use the above json as a body of a POST and use postman to hit circle's api.
`https://circleci.com/api/v1.1/project/github/ncino/force-release-plm-test/tree/1.9-pre?circle-token=cdba83bdc9ae3f9109b909be45cec7ab7b908ba4`
Note the circleci token ^ and that the branch is using a tag instead of the actual branch.

To test a failure I like to break the src/classes/Greetings.cls by commenting out a bracket.

### CODE REVIEW

**Comment by matthew-craig-ncino** [comment]
Looks good so far.

**Comment by dalefrancum-ncino** [comment]
Kevin, this looks good. I have a suggestion for simplifying the Bash code under the deployment step. It looks like there are only two differences between patch deployment vs. release deployment. Assuming that is correct, I believe this would work:

```
      - deploy:
          name: Deploy to packaging, run logic to update jira ticket and deployments dynamodb table based on pass or fail
          command: |
            if [[ $CIRCLE_BRANCH =~ $PATCH_TAG_REGEX ]]; then
              sfdeploy_prefix="PATCH"
            else
              sfdeploy_prefix="RELEASE"
            fi
            echo "Deploying to $sfdeploy_prefix org"
            if sfdeploy -pre $sfdeploy_prefix -fn "$RELEASE_FULLNAME" -pi "$POST_INSTALL_CLASS" -d deploy_sfdc_js_release_ci -lt $LOG_TYPE -ll $LOG_LEVEL -lp $DEPLOYMENT_LOG -ci; then
              echo "Deploy Passed"
              # STUBBED devops_lib_script_update_dynamo_record.succuess($DEPLOYMENT_RECORD_ID)
              if [[ ${UPDATE_JIRA_ISSUES} = [Tt][Rr][Uu][Ee] ]]; then
                echo "jira issues updating..."
                # STUBBED jira_updater.succuess(JIRA_ISSUE_DATA)
              fi
              if [[ ${TRIGGER_PACKAGE_BUILD} = [Tt][Rr][Uu][Ee] ]]; then
                echo "Polling package build..."
                # STUBBED devop_lib_script to hit tooling api in packaging org
              fi
            else
              echo "Deploy failed, logging in deployments table and reverting jira ticket progression" && touch $FAILURE_FILE && exit 1
              # STUBBED devops_lib_script_update_dynamo_record.failure($DEPLOYMENT_RECORD_ID)
              # STUBBED jira_updater.failure(JIRA_ISSUE_DATA) && touch $FAILURE_FILE && exit 1
            fi
```

**Comment by dalefrancum-ncino** [comment]
The next thing I would recommend working on is what the incoming JSON (sent into CircleCI's ```build_parameters```) should look like. For example, you'll need a list of Jira issues to update. The build should also be told what the Jira values are to be used in the updates.

Maybe all this can just be documented in the ticket. Once you have it though you can submit test requests using Postman, and you can un-STUB the jira_updater calls.

**Comment by Kevmo92** [comment]
@dalefrancum-ncino Great points Dale! I'll work on getting those in place.

**Comment by dalefrancum-ncino** [comment]
@Kevmo92 - the changes look good!

**Pull request merged**
